import Head from 'next/head'
import NavBar from "../../components/organisms/navigation/navigation";
import React from "react";
import Market from "../../components/pages/market/market";
import SideFilter from "../../components/organisms/sideFilter/sideFilter";
interface AppProps {
    children: React.ReactNode
}

export default function Home({children}: AppProps) {
    return (
        <>
            <Head>
                <title>Market</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/logo.png"/>
            </Head>
            <main className=" h-screen overflow-hidden bg-zinc-900 flex flex-col">
                <NavBar/>
                <div className="flex flex-row">
                    <div className=" w-[60%] px-4 py-2">
                        <SideFilter/>
                    </div>
                    <Market/>
                </div>

            </main>
        </>
    )
}
